service: serverless-mysql-todos-mamer
frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs4.3
  environment:
    dev:
      MYSQL_DB: 'sls_todos_mysql'
      TABLE_NAME: 'Todos'
      SLS_DEBUG: true
      SECRET_VAR: 'secret in dev'
      AWESOME_VAR: 'gwapo ni mamer'

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
          cors: true

  create:
    handler: todos/src/create.create
    events:
      - http:
          path: todos
          method: post
          cors: true

  list:
    handler: todos/src/list.list
    events:
      - http:
          path: todos
          method: get
          cors: true

  get:
    handler: todos/src/get.get
    events:
      - http:
          path: todos/{id}
          method: get
          cors: true

  update:
    handler: todos/src/update.update
    events:
      - http:
          path: todos/{id}
          method: put
          cors: true

  delete:
    handler: todos/src/delete.delete
    events:
      - http:
          path: todos/{id}
          method: delete
          cors: true

  generate:
    handler: handler.generate
    events:
      - http:
          path: process
          method: post
          contentHandling: CONVERT_TO_BINARY
          cors: true

custom:
  custom:
    apigwBinary:
      types:
        - 'application/octet-stream'
        - 'application/zip'
        - 'image/png'
        - 'image/jpeg'

plugins:
  - serverless-apigw-binary
  - serverless-apigwy-binary
  - serverless-plugin-bespoken
