service: serverless-mysql-todos-mamer
frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs4.3
  environment: ${file(./sls/env.yml):${opt:stage}}
  vpc: ${file(./sls/prvdr.yml):VPC}
  iamRoleStatements: ${file(./sls/prvdr.yml):IAM}

functions: ${file(./sls/fxn.yml)}
custom: ${file(./sls/custom.yml)}
resources: ${file(./sls/rsrc.yml)}
plugins:
  # ${file(./sls/plugins.yml)}
  - serverless-offline
  - serverless-apigw-binary
  - serverless-apigwy-binary

